[server]
headless = true
maxUploadSize = 50

[theme]
primaryColor = "#4e8cff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
